/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pa.cifpaviles.dam.diact1_2;

/**
 *
 * @author danielgarcia
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAniadir = new javax.swing.JButton();
        lblNombreAlumno = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellidosAlumno = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblEmailAlumno = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEdadAlumno = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        lblTelefonoAlumno = new javax.swing.JLabel();
        lblErrorMaxAlumnos = new javax.swing.JLabel();
        lblAlumnoJoven = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAniadir.setText("Añadir alumno");
        btnAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAniadirActionPerformed(evt);
            }
        });

        lblNombreAlumno.setText("Introduzca el nombre del alumno");

        lblApellidosAlumno.setText("Introduzca los apellidos del alumno");

        lblEmailAlumno.setText("Introduzca el email del alumno");

        lblEdadAlumno.setText("Introduzca la edad del alumno");

        lblTelefonoAlumno.setText("Introduzca el teléfono del alumno");

        lblErrorMaxAlumnos.setForeground(java.awt.Color.red);
        lblErrorMaxAlumnos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(376, 376, 376)
                .addComponent(btnAniadir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAlumnoJoven, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMaxAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblTelefonoAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblEmailAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNombre)
                                        .addComponent(lblNombreAlumno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEdadAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtApellidos)
                                                .addComponent(lblApellidosAlumno))
                                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(258, 258, 258))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(lblAlumnoJoven, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblApellidosAlumno)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEdadAlumno)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblEmailAlumno))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTelefonoAlumno))
                .addGap(34, 34, 34)
                .addComponent(btnAniadir)
                .addGap(18, 18, 18)
                .addComponent(lblErrorMaxAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAniadirActionPerformed
       
        String nombre=txtNombre.getText();
        String apellidos=txtApellidos.getText();
        String email=txtEmail.getText();
        int edad=Integer.parseInt(txtEdad.getText());
        String telefono=txtTelefono.getText();
         
            Alumno a=new Alumno(nombre,apellidos ,email ,edad ,telefono );
            Principal.ArrayAlumnos[ContadorAlumno]= a;
            
            AlumnoJoven(a);
            ContadorAlumno++;

            MaxAlumnos();
        
        for(int i=0;i<Principal.ArrayAlumnos.length;i++)
        {
            System.out.println(Principal.ArrayAlumnos[i]);
        }
    }//GEN-LAST:event_btnAniadirActionPerformed

    static int ContadorAlumno=0;
    public void AlumnoJoven(Alumno a)
    {
        int edadmenor=100;
        if(Principal.ArrayAlumnos[ContadorAlumno].getEdad()<edadmenor)
        {
            edadmenor=Principal.ArrayAlumnos[ContadorAlumno].getEdad();
            lblAlumnoJoven.setText("El alumno más joven es "
                    +Principal.ArrayAlumnos[ContadorAlumno].getNombre()
                    +" "+Principal.ArrayAlumnos[ContadorAlumno].getApellidos()
                    +" con "+Principal.ArrayAlumnos[ContadorAlumno].getEdad()+" años");
        }
    }
    
    public void MaxAlumnos()
    {
        if (ContadorAlumno==5)
        {
            lblErrorMaxAlumnos.setText("Máximo de alumnos alcanzado(5)");
            btnAniadir.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAniadir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAlumnoJoven;
    private javax.swing.JLabel lblApellidosAlumno;
    private javax.swing.JLabel lblEdadAlumno;
    private javax.swing.JLabel lblEmailAlumno;
    private javax.swing.JLabel lblErrorMaxAlumnos;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblTelefonoAlumno;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
//
//    /**
//     * @return the txtApellidos
//     */
//    public javax.swing.JTextField getTxtApellidos() {
//        return txtApellidos;
//    }
//
//    /**
//     * @param txtApellidos the txtApellidos to set
//     */
//    public void setTxtApellidos(javax.swing.JTextField txtApellidos) {
//        this.txtApellidos = txtApellidos;
//    }
//
//    /**
//     * @return the txtEdad
//     */
//    public javax.swing.JTextField getTxtEdad() {
//        return txtEdad;
//    }
//
//    /**
//     * @param txtEdad the txtEdad to set
//     */
//    public void setTxtEdad(javax.swing.JTextField txtEdad) {
//        this.txtEdad = txtEdad;
//    }
//
//    /**
//     * @return the txtEmail
//     */
//    public javax.swing.JTextField getTxtEmail() {
//        return txtEmail;
//    }
//
//    /**
//     * @param txtEmail the txtEmail to set
//     */
//    public void setTxtEmail(javax.swing.JTextField txtEmail) {
//        this.txtEmail = txtEmail;
//    }
//
//    /**
//     * @return the txtNombre
//     */
//    public  javax.swing.JTextField getTxtNombre() {
//        return txtNombre;
//    }
//
//    /**
//     * @param txtNombre the txtNombre to set
//     */
//    public void setTxtNombre(javax.swing.JTextField txtNombre) {
//        this.txtNombre = txtNombre;
//    }
//
//    /**
//     * @return the txtTelefono
//     */
//    public javax.swing.JTextField getTxtTelefono() {
//        return txtTelefono;
//    }
//
//    /**
//     * @param txtTelefono the txtTelefono to set
//     */
//    public void setTxtTelefono(javax.swing.JTextField txtTelefono) {
//        this.txtTelefono = txtTelefono;
//    }


    
    
    


}
